"""add unique constraints to ems organizations

Revision ID: 1f7ab98850d1
Revises: 37cd3f722278
Create Date: 2026-07-23 23:11:33.750885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7ab98850d1'
down_revision: Union[str, Sequence[str], None] = '37cd3f722278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ems_organizations', ['email'])
    op.create_unique_constraint(None, 'ems_organizations', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ems_organizations', type_='unique')
    op.drop_constraint(None, 'ems_organizations', type_='unique')
    # ### end Alembic commands ###
