"""create hospitals table

Revision ID: 436f71aea241
Revises: 1f7ab98850d1
Create Date: 2026-07-23 23:35:25.616561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436f71aea241'
down_revision: Union[str, Sequence[str], None] = '1f7ab98850d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('code', sa.String(length=20), nullable=False))
    op.add_column('hospitals', sa.Column('ems_organization_id', sa.UUID(), nullable=False))
    op.alter_column('hospitals', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_unique_constraint(None, 'hospitals', ['code'])
    op.create_unique_constraint(None, 'hospitals', ['phone'])
    op.create_unique_constraint(None, 'hospitals', ['email'])
    op.create_foreign_key(None, 'hospitals', 'ems_organizations', ['ems_organization_id'], ['id'])
    op.drop_column('hospitals', 'total_beds')
    op.drop_column('hospitals', 'available_beds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('available_beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hospitals', sa.Column('total_beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.alter_column('hospitals', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('hospitals', 'ems_organization_id')
    op.drop_column('hospitals', 'code')
    # ### end Alembic commands ###
