"""create ambulances table

Revision ID: 8225039a6cc2
Revises: b0f850db3a6b
Create Date: 2026-07-24 22:57:12.183635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8225039a6cc2'
down_revision: Union[str, Sequence[str], None] = 'b0f850db3a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BLS', 'ALS', 'ICU', 'BIKE', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'DISPATCHED', 'ON_ROUTE', 'AT_SCENE', 'TRANSPORTING', 'AT_HOSPITAL', 'MAINTENANCE', 'OUT_OF_SERVICE', name='ambulancestatus'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('ems_organization_id', sa.UUID(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ems_organization_id'], ['ems_organizations.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_foreign_key(None, 'dispatch_assignments', 'ambulances', ['ambulance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dispatch_assignments', type_='foreignkey')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
