"""create emergency_cases table

Revision ID: 95641a968513
Revises: da907d607690
Create Date: 2026-07-24 23:12:52.458127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95641a968513'
down_revision: Union[str, Sequence[str], None] = 'da907d607690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('reporter_name', sa.String(length=100), nullable=False),
    sa.Column('reporter_phone', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=20), nullable=True),
    sa.Column('incident_type', sa.Enum('ACCIDENT', 'CARDIAC', 'FIRE', 'STROKE', 'TRAUMA', 'PREGNANCY', 'POISONING', 'RESPIRATORY', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'VERIFIED', 'DISPATCHED', 'AMBULANCE_ARRIVED', 'PATIENT_PICKED', 'HOSPITAL_ASSIGNED', 'COMPLETED', 'CANCELLED', name='emergencystatus'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_cases')
    # ### end Alembic commands ###
